name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix permissions
        run: chmod -R a+rw ${PWD}
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_TEST }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_TEST }}
          VERSION: ${{ github.ref_name }}
        run: make deploy
      - name: Build an addon
        env:
          VERSION: ${{ github.ref_name }}
        run: make video_addon
      - name: List files
        run: ls -lh
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: video.kino.pub-${{ github.ref_name }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
