name: tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Pre-commit checks
        uses: pre-commit/action@v2.0.0
      - name: Analysis (git diff)
        if: failure()
        run: git diff
